"""add paypal_link to submissions

Revision ID: d0a34e163aa4
Revises: 4fe76d95a65d
Create Date: 2026-04-04 17:15:32.382427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a34e163aa4'
down_revision: Union[str, Sequence[str], None] = '4fe76d95a65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('paypal_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'paypal_link')
    # ### end Alembic commands ###
